package mv;
import ru.ifmo.se.pokemon.*;

public class DragonPulse extends SpecialMove {

	public DragonPulse () {
		super(Type.DRAGON, 85.0, 100.0);
	}

	@Override
	protected String describe () {
		return "attacks the target with a shock wave "
		     + "generated by its gaping mouth";
	}
}
